"""
Turns a run into a Markdown scorecard.

Markdown because it renders nicely on GitHub, in pull requests,
and in most CI tools, and it is still readable as plain text.
"""

from pathlib import Path


def pct(value: float) -> str:
    return f"{value * 100:.0f}%"


def cell(text: str, limit: int = 60) -> str:
    """Make text safe for a Markdown table cell and keep it short."""
    text = " ".join(str(text).split()).replace("|", "\\|")
    return text if len(text) <= limit else text[: limit - 1] + "…"


def to_markdown(run: dict) -> str:
    s = run["summary"]
    rubric = run["rubric"]
    verdict = "PASS" if s["failed"] == 0 else f"{s['failed']} FAILED"
    lines: list[str] = []

    lines += [
        f"# Scorecard: {run['name']}",
        "",
        f"**Result: {verdict}.** {s['passed']} of {s['total']} cases passed ({pct(s['pass_rate'])}), "
        f"mean score {s['mean_score']:.2f}",
        "",
        f"- Dataset: `{run.get('dataset') or '-'}`",
        f"- Answers: `{run.get('answers') or '-'}`",
        f"- Rubric: {rubric['name']} (pass mark {rubric['pass_threshold']:.2f})",
        f"- Created: {run['created_at']}",
        "",
    ]

    for warning in run.get("warnings", []):
        lines.append(f"> Warning: {warning}")
    if run.get("warnings"):
        lines.append("")

    # Metric table
    lines += ["## Metrics", "", "| Metric | Weight | Min | Mean score |", "|---|---:|---:|---:|"]
    for name, settings in rubric["metrics"].items():
        mean = s["metric_means"].get(name)
        minimum = settings.get("min")
        lines.append(
            f"| {name} | {settings['weight']:g} | {'-' if minimum is None else f'{minimum:.2f}'} | "
            f"{'n/a' if mean is None else f'{mean:.2f}'} |"
        )
    lines.append("")

    # Case table
    metric_names = list(rubric["metrics"])
    header = "| | Case | Score | " + " | ".join(metric_names) + " |"
    divider = "|---|---|---:|" + "---:|" * len(metric_names)
    lines += ["## Cases", "", header, divider]
    for case in run["cases"]:
        by_name = {m["name"]: m for m in case["metrics"]}
        values = []
        for name in metric_names:
            m = by_name.get(name)
            if m is None or m["score"] is None:
                values.append("-")
            else:
                values.append(f"{m['score']:.2f}" + (" ⚠" if m["below_minimum"] else ""))
        mark = "✅" if case["passed"] else "❌"
        lines.append(f"| {mark} | {cell(case['id'], 30)} | {case['score']:.2f} | " + " | ".join(values) + " |")
    lines.append("")

    # Failure details
    failures = [c for c in run["cases"] if not c["passed"]]
    if failures:
        lines += ["## Why cases failed", ""]
        for case in failures:
            lines.append(f"### ❌ {case['id']}")
            lines.append(f"- **Question:** {cell(case['question'], 200)}")
            lines.append(f"- **Expected:** {cell(case['reference'], 200)}")
            lines.append(f"- **Got:** {cell(case['answer'] if case['answer'] is not None else '(no answer)', 200)}")
            for reason in case["reasons"]:
                lines.append(f"- {reason}")
            lines.append("")

    if s["by_tag"]:
        lines += ["## By tag", "", "| Tag | Passed | Pass rate |", "|---|---:|---:|"]
        for tag, stats in s["by_tag"].items():
            lines.append(f"| {tag} | {stats['passed']}/{stats['total']} | {pct(stats['pass_rate'])} |")
        lines.append("")

    lines.append("_Generated by RubricSmith._")
    return "\n".join(lines) + "\n"


def write_markdown(run: dict, path: Path | str) -> Path:
    path = Path(path)
    path.write_text(to_markdown(run), encoding="utf-8")
    return path
